//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremeAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carro()
        {
            this.RegistroMantenimiento = new HashSet<RegistroMantenimiento>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int IDCarro { get; set; }
        public string Modelo { get; set; }
        public string Tipo { get; set; }
        public string TipoRueda { get; set; }
        public string Placa { get; set; }
        public string Color { get; set; }
        public decimal Precio { get; set; }
        public Nullable<int> IDSeguro { get; set; }
    
        public virtual Seguro Seguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroMantenimiento> RegistroMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
