//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremeAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroMantenimiento
    {
        public int IDRegistroMantenimiento { get; set; }
        public string Descripcion { get; set; }
        public decimal Costo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string IDCliente { get; set; }
        public int IDCarro { get; set; }
        public string IDEmpleado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Carro Carro { get; set; }
    }
}
