//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremeAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int IDTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IDTarjeta { get; set; }
        public int IDVenta { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
